additionalScrapeConfigs:
  - job_name: 'default-namespace'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: default
