apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-website
spec:
  replicas: {{ .Values.websiteService.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-website
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-website
    spec:
      containers:
      - name: website-service
        image: "{{ .Values.websiteService.image.repository }}:{{ .Values.websiteService.image.tag }}"
        imagePullPolicy: {{ .Values.websiteService.image.pullPolicy }}
        ports:
        - containerPort: 8080